// IKKON blog — UI strings, taxonomy and posts (PT / EN / JA)
window.IKKON_BLOG = {
  ui: {
    pt: {
      blog: 'Blog',
      hero: {
        eyebrow: 'DIÁRIO DO DOJO',
        title: 'Blog',
        subtitle: 'Método, bastidores de palco e cultura japonesa contados por quem toca taiko todos os dias em São Paulo.',
        cta1: 'Ver publicações',
        cta2: 'Conheça a escola',
      },
      featured: { title: 'Destaques', support: 'As leituras que melhor explicam o que fazemos no dojo — comece por aqui.', badge: 'Destaque' },
      week: { title: 'Blog da semana', desc: 'Três textos curtos que estamos comentando nas aulas desta semana. Leitura de cinco minutos entre um treino e outro.', badge: 'Semana' },
      filters: {
        title: 'Filtrar publicações',
        hint: 'Busque por título, tema ou tag — ou escolha uma categoria abaixo.',
        placeholder: 'Buscar publicações',
        search: 'Pesquisar',
        allCats: 'Todas as categorias',
        allTags: 'Todas as tags',
        clear: 'Limpar filtros',
      },
      results: { one: '1 publicação', many: '{n} publicações', sort: 'Ordenado por: mais recentes' },
      empty: {
        title: 'Nenhuma publicação encontrada',
        text: 'Não encontramos textos com esses termos. Tente outra palavra ou remova os filtros ativos.',
        cta: 'Ver todos os posts',
      },
      by: 'por',
      read: '{n} min de leitura',
      fallback: 'Sem imagem de capa',
      pagePrefix: 'Página',
    },
    en: {
      blog: 'Blog',
      hero: {
        eyebrow: 'DOJO JOURNAL',
        title: 'Blog',
        subtitle: 'Method, backstage notes and Japanese culture, written by people who play taiko every day in São Paulo.',
        cta1: 'See the posts',
        cta2: 'Meet the school',
      },
      featured: { title: 'Featured', support: 'The reads that best explain what we do in the dojo — start here.', badge: 'Featured' },
      week: { title: 'Blog of the week', desc: 'Three short texts we are discussing in class this week. A five-minute read between drills.', badge: 'Week' },
      filters: {
        title: 'Filter posts',
        hint: 'Search by title, theme or tag — or pick a category below.',
        placeholder: 'Search posts',
        search: 'Search',
        allCats: 'All categories',
        allTags: 'All tags',
        clear: 'Clear filters',
      },
      results: { one: '1 post', many: '{n} posts', sort: 'Sorted by: most recent' },
      empty: {
        title: 'No posts found',
        text: 'We found no texts matching those terms. Try another word or clear the active filters.',
        cta: 'See all posts',
      },
      by: 'by',
      read: '{n} min read',
      fallback: 'No cover image',
      pagePrefix: 'Page',
    },
    ja: {
      blog: 'ブログ',
      hero: {
        eyebrow: '道場日記',
        title: 'ブログ',
        subtitle: 'サンパウロで毎日太鼓を打つ私たちが綴る、指導法・舞台裏・日本文化の記録。',
        cta1: '記事を見る',
        cta2: '道場について',
      },
      featured: { title: '注目の記事', support: '道場の活動がいちばん伝わる記事です。まずはここから。', badge: '注目' },
      week: { title: '今週のブログ', desc: '今週のレッスンで話題にしている短い記事を3本。稽古の合間に5分で読めます。', badge: '今週' },
      filters: {
        title: '記事を絞り込む',
        hint: 'タイトル・テーマ・タグで検索、または下のカテゴリーから選んでください。',
        placeholder: '記事を検索',
        search: '検索',
        allCats: 'すべてのカテゴリー',
        allTags: 'すべてのタグ',
        clear: '絞り込みを解除',
      },
      results: { one: '記事 1 件', many: '記事 {n} 件', sort: '並び順：新しい順' },
      empty: {
        title: '記事が見つかりません',
        text: 'その条件に一致する記事はありませんでした。別のキーワードをお試しか、絞り込みを解除してください。',
        cta: 'すべての記事を見る',
      },
      by: '執筆',
      read: '約{n}分',
      fallback: '表紙画像なし',
      pagePrefix: 'ページ',
    },
  },

  categories: [
    { id: 'metodo', label: { pt: 'Método', en: 'Method', ja: '指導法' } },
    { id: 'palco', label: { pt: 'Palco', en: 'Stage', ja: '舞台' } },
    { id: 'cultura', label: { pt: 'Cultura', en: 'Culture', ja: '文化' } },
    { id: 'dojo', label: { pt: 'Vida no dojo', en: 'Dojo life', ja: '道場の日々' } },
    { id: 'comunidade', label: { pt: 'Comunidade', en: 'Community', ja: '地域' } },
  ],

  tags: [
    { id: 'iniciantes', label: { pt: 'iniciantes', en: 'beginners', ja: '初心者' } },
    { id: 'tecnica', label: { pt: 'técnica', en: 'technique', ja: '技術' } },
    { id: 'japao', label: { pt: 'japão', en: 'japan', ja: '日本' } },
    { id: 'ensemble', label: { pt: 'ensemble', en: 'ensemble', ja: 'アンサンブル' } },
    { id: 'historia', label: { pt: 'história', en: 'history', ja: '歴史' } },
    { id: 'inclusao', label: { pt: 'inclusão', en: 'inclusion', ja: 'インクルージョン' } },
    { id: 'alunos', label: { pt: 'alunos', en: 'students', ja: '生徒' } },
    { id: 'equipamento', label: { pt: 'equipamento', en: 'gear', ja: '道具' } },
  ],

  posts: [
    {
      id: 'alfabetizacao-musical',
      date: '2026-07-18', author: 'Felipe Fugimoto', cat: 'metodo', tags: ['iniciantes', 'tecnica'],
      minutes: 8, featured: true, slot: true,
      title: {
        pt: 'Alfabetização Musical: como ensinamos taiko a quem nunca tocou nada',
        en: 'Musical Literacy: teaching taiko to people who never played anything',
        ja: '音楽リテラシー：楽器未経験者に太鼓を教える方法',
      },
      excerpt: {
        pt: 'Nosso método começa antes do primeiro golpe: entender o pulso, nomear o que se ouve e transformar a contagem em corpo. Um panorama das quatro etapas que estruturam as aulas do dojo.',
        en: 'Our method starts before the first strike: feeling the pulse, naming what you hear and turning counting into body movement. An overview of the four stages that structure classes at the dojo.',
        ja: '私たちの指導は最初の一打より前から始まります。拍を感じ、聞こえた音に名前をつけ、数えることを身体の動きに変える。道場のレッスンを支える4つの段階を紹介します。',
      },
    },
    {
      id: 'earth-celebration',
      date: '2026-07-05', author: 'Kenzo Torigoe', cat: 'palco', tags: ['japao', 'ensemble'],
      minutes: 7, featured: true, slot: true,
      title: {
        pt: 'Earth Celebration: o primeiro grupo brasileiro em performance solo',
        en: 'Earth Celebration: the first Brazilian group to perform solo',
        ja: 'アース・セレブレーション：ブラジル勢初の単独公演',
      },
      excerpt: {
        pt: 'Sado, ilha do Kodo, palco de terra batida e um repertório que precisou caber em vinte minutos. O relato de bastidores de uma estreia que levou onze anos para acontecer.',
        en: 'Sado, Kodo\'s island, a packed-earth stage and a repertoire that had to fit into twenty minutes. The backstage account of a debut eleven years in the making.',
        ja: '佐渡島、鼓童の島、土の舞台、そして20分に収めなければならなかった演目。11年かけて実現した初舞台の裏側を綴ります。',
      },
    },
    {
      id: 'pipa-taiko',
      date: '2026-06-27', author: 'Miyuki Maeda', cat: 'comunidade', tags: ['inclusao', 'alunos'],
      minutes: 5, weekly: true, slot: true,
      title: {
        pt: 'PIPA Taiko: um ano de oficinas para crianças autistas',
        en: 'PIPA Taiko: one year of workshops for autistic children',
        ja: 'PIPA Taiko：自閉症の子どもたちとの1年',
      },
      excerpt: {
        pt: 'O que aprendemos sobre volume, previsibilidade e tempo de espera ao adaptar o taiko para outro ritmo de atenção.',
        en: 'What we learned about volume, predictability and waiting time while adapting taiko to a different rhythm of attention.',
        ja: '音量、見通しやすさ、待つ時間——別の注意のリズムに太鼓を合わせて学んだこと。',
      },
    },
    {
      id: 'respiracao-kiai',
      date: '2026-06-14', author: 'Marcos Joaquim', cat: 'metodo', tags: ['tecnica', 'iniciantes'],
      minutes: 6, weekly: true, slot: true,
      title: {
        pt: 'Respiração e kiai: por que o grito não é decoração',
        en: 'Breath and kiai: why the shout is not decoration',
        ja: '呼吸と気合：掛け声は飾りではない',
      },
      excerpt: {
        pt: 'O kiai organiza o grupo, marca a entrada e sustenta a postura. Três exercícios para tirar a voz do lugar de vergonha.',
        en: 'Kiai organizes the group, marks the entrance and holds the posture. Three exercises to move your voice past embarrassment.',
        ja: '気合は集団をまとめ、入りを示し、姿勢を支えます。声の照れをほどく3つの練習。',
      },
    },
    {
      id: 'matsuri-ritmos',
      date: '2026-05-30', author: 'Felipe Fugimoto', cat: 'cultura', tags: ['historia', 'japao'],
      minutes: 9, weekly: true,
      title: {
        pt: 'Os ritmos que vieram do matsuri',
        en: 'The rhythms that came from matsuri',
        ja: '祭りから生まれたリズム',
      },
      excerpt: {
        pt: 'Antes do palco, o taiko era festa de rua. Um mapa curto dos padrões regionais que ainda tocamos hoje.',
        en: 'Before the stage, taiko was a street festival. A short map of the regional patterns we still play today.',
        ja: '舞台の前、太鼓は町の祭りでした。今も打ち続ける地方の型を短く辿ります。',
      },
    },
    {
      id: 'primeira-aula',
      date: '2026-05-16', author: 'Miyuki Maeda', cat: 'dojo', tags: ['iniciantes', 'alunos'],
      minutes: 4, slot: true,
      title: {
        pt: 'O que esperar da sua primeira aula de taiko',
        en: 'What to expect from your first taiko class',
        ja: '初めての太鼓レッスンで起こること',
      },
      excerpt: {
        pt: 'Roupa, horário, o que trazer e o que ninguém conta: você vai errar o tempo nos primeiros dez minutos, e isso está previsto no plano de aula.',
        en: 'Clothing, timing, what to bring — and what nobody tells you: you will lose the beat in the first ten minutes, and that is part of the lesson plan.',
        ja: '服装、時間、持ち物、そして誰も言わないこと。最初の10分で拍を外します。それも計画のうちです。',
      },
    },
    {
      id: 'bachi-cuidados',
      date: '2026-05-02', author: 'Marcos Joaquim', cat: 'dojo', tags: ['equipamento', 'tecnica'],
      minutes: 5,
      title: {
        pt: 'Bachi: como escolher, cuidar e saber quando aposentar',
        en: 'Bachi: how to choose them, care for them and know when to retire them',
        ja: '撥（バチ）の選び方・手入れ・引退の見きわめ',
      },
      excerpt: {
        pt: 'Peso, madeira e diâmetro mudam o som antes de qualquer técnica. Um guia prático para quem vai comprar o primeiro par.',
        en: 'Weight, wood and diameter change the sound before any technique does. A practical guide for buying your first pair.',
        ja: '重さ、木材、太さは技術より先に音を変えます。最初の一組を買う人のための実践ガイド。',
      },
    },
    {
      id: 'festival-do-japao',
      date: '2026-04-19', author: 'Kenzo Torigoe', cat: 'palco', tags: ['ensemble', 'alunos'],
      minutes: 6, slot: true,
      title: {
        pt: 'Festival do Japão: três dias, quatro palcos, cinquenta alunos',
        en: 'Festival do Japão: three days, four stages, fifty students',
        ja: '日本祭り：3日間、4ステージ、生徒50名',
      },
      excerpt: {
        pt: 'Como se monta a logística de um festival com turmas de níveis diferentes tocando no mesmo fim de semana.',
        en: 'How we build the logistics of a festival with groups of different levels playing on the same weekend.',
        ja: 'レベルの違うクラスが同じ週末に出演する祭りの、段取りの立て方。',
      },
    },
    {
      id: 'kumidaiko',
      date: '2026-04-04', author: 'Felipe Fugimoto', cat: 'cultura', tags: ['historia'],
      minutes: 10,
      title: {
        pt: 'Kumidaiko tem menos de 75 anos — e isso muda tudo',
        en: 'Kumidaiko is less than 75 years old — and that changes everything',
        ja: '組太鼓は75年に満たない——その事実が変えること',
      },
      excerpt: {
        pt: 'O conjunto de tambores como conhecemos é invenção do pós-guerra. Entender essa data ajuda a separar tradição de hábito.',
        en: 'The drum ensemble as we know it is a post-war invention. Understanding that date helps separate tradition from habit.',
        ja: '今日の組太鼓は戦後の発明です。その年代を知ることで、伝統と習慣を切り分けられます。',
      },
    },
    {
      id: 'recital-interno',
      date: '2026-03-21', author: 'Miyuki Maeda', cat: 'dojo', tags: ['alunos'],
      minutes: 4,
      title: {
        pt: 'Recital interno: o palco pequeno que prepara o grande',
        en: 'Internal recital: the small stage that prepares the big one',
        ja: '内部発表会：大舞台を支える小さな舞台',
      },
      excerpt: {
        pt: 'Duas vezes por ano o dojo vira plateia. Uma nota sobre nervosismo, memória muscular e aplauso de quem te viu errar.',
        en: 'Twice a year the dojo becomes an audience. A note on nerves, muscle memory and applause from people who watched you fail.',
        ja: '年に2回、道場は客席になります。緊張、身体の記憶、そして失敗を見てきた人の拍手について。',
      },
    },
    {
      id: 'kodomo-no-sono',
      date: '2026-03-07', author: 'Marcos Joaquim', cat: 'comunidade', tags: ['inclusao'],
      minutes: 6,
      title: {
        pt: 'Kodomo-no-Sono: quatro anos de oficinas gratuitas',
        en: 'Kodomo-no-Sono: four years of free workshops',
        ja: 'コドモノソノ：無料ワークショップの4年',
      },
      excerpt: {
        pt: 'Um balanço do projeto com jovens e adultos com deficiência intelectual, e o que ele ensinou ao nosso método regular.',
        en: 'A review of the project with youths and adults with intellectual disabilities, and what it taught our regular method.',
        ja: '知的障がいのある若者・成人との取り組みを振り返り、通常の指導法に還ったことを記します。',
      },
    },
    {
      id: 'kata-postura',
      date: '2026-02-21', author: 'Kenzo Torigoe', cat: 'metodo', tags: ['tecnica'],
      minutes: 7,
      title: {
        pt: 'Kata não é pose: a postura como economia de energia',
        en: 'Kata is not a pose: posture as energy economy',
        ja: '型はポーズではない：姿勢というエネルギー効率',
      },
      excerpt: {
        pt: 'Quem toca vinte minutos seguidos aprende rápido: a postura correta é a que cansa menos, não a que parece melhor na foto.',
        en: 'Anyone who plays for twenty straight minutes learns fast: correct posture is the one that tires you least, not the one that photographs best.',
        ja: '20分打ち続ければすぐ分かります。正しい姿勢とは、写真映えする形ではなく、いちばん疲れない形です。',
      },
    },
  ],
};
