// <auto-generated />
using System;
using IkkonAdmin.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IkkonAdmin.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260805015740_AddAuditCorrelation")]
    partial class AddAuditCorrelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.AcordoFinanceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly?>("FimVigencia")
                        .HasColumnType("date");

                    b.Property<DateOnly>("InicioVigencia")
                        .HasColumnType("date");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorMensalAcordado")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("AcordosFinanceiros", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Admissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlunoId")
                        .HasColumnType("int");

                    b.Property<string>("ChecklistObservacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ContratoAssinado")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("DataAulaExperimental")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataMatricula")
                        .HasColumnType("date");

                    b.Property<bool>("IntegracaoConcluida")
                        .HasColumnType("bit");

                    b.Property<string>("NomeInteressado")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("PagamentoInicialConfirmado")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("Admissoes", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContatoEmergencia")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly>("DataEntrada")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RG")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TurmaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.HasIndex("TurmaId");

                    b.ToTable("Alunos", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.AlunoInsignia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ConcedidaEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ConcedidaPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("InsigniaId")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Origem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConcedidaPorUsuarioId");

                    b.HasIndex("InsigniaId");

                    b.HasIndex("AlunoId", "InsigniaId")
                        .IsUnique();

                    b.ToTable("AlunoInsignias", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.AlunoTurma", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("TurmaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataVinculo")
                        .HasColumnType("datetime2");

                    b.HasKey("AlunoId", "TurmaId");

                    b.HasIndex("TurmaId");

                    b.ToTable("AlunosTurmas", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.AuditoriaLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DadosAntesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DadosDepoisJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataEventoUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("EnderecoIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("EntidadeId")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("UsuarioAfetadoId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioResponsavelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("DataEventoUtc");

                    b.HasIndex("UsuarioAfetadoId");

                    b.HasIndex("UsuarioResponsavelId");

                    b.HasIndex("Entidade", "Acao");

                    b.ToTable("AuditoriaLogs", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Aula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InstrutorUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("Local")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TurmaHorarioId")
                        .HasColumnType("int");

                    b.Property<int>("TurmaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstrutorUsuarioId");

                    b.HasIndex("Status");

                    b.HasIndex("TurmaHorarioId");

                    b.HasIndex("TurmaId", "Inicio");

                    b.ToTable("Aulas", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.BlogCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("BlogCategories", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuthorDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("AuthorUserId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ContentHtml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWeeklyHighlight")
                        .HasColumnType("bit");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("pt-BR");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReadingTimeMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("ScheduledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SeoDescription")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("SeoTitle")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<int?>("TranslationGroupId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LanguageCode");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("IsFeatured", "PublishedAtUtc");

                    b.HasIndex("IsWeeklyHighlight", "PublishedAtUtc");

                    b.HasIndex("TranslationGroupId", "LanguageCode");

                    b.HasIndex("Status", "PublishedAtUtc", "DeletedAtUtc");

                    b.ToTable("BlogPosts", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.BlogPostTag", b =>
                {
                    b.Property<int>("BlogPostId")
                        .HasColumnType("int");

                    b.Property<int>("BlogTagId")
                        .HasColumnType("int");

                    b.HasKey("BlogPostId", "BlogTagId");

                    b.HasIndex("BlogTagId");

                    b.ToTable("BlogPostTags", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.BlogTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("BlogTags", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Comunicado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("CriadoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiraEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Fixado")
                        .HasColumnType("bit");

                    b.Property<bool>("Importante")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublicadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorUsuarioId");

                    b.HasIndex("Ativo", "PublicadoEmUtc", "ExpiraEmUtc");

                    b.ToTable("Comunicados", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.ComunicadoAlvo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("ComunicadoId")
                        .HasColumnType("int");

                    b.Property<bool>("Todos")
                        .HasColumnType("bit");

                    b.Property<int?>("TurmaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("TurmaId");

                    b.HasIndex("ComunicadoId", "AlunoId", "TurmaId", "Todos");

                    b.ToTable("ComunicadosAlvos", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.ComunicadoLeitura", b =>
                {
                    b.Property<int>("ComunicadoId")
                        .HasColumnType("int");

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LidoEmUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("ComunicadoId", "AlunoId");

                    b.HasIndex("AlunoId");

                    b.ToTable("ComunicadosLeituras", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.ConfiguracaoSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AplicarMultaJurosAutomaticamente")
                        .HasColumnType("bit");

                    b.Property<bool>("AtualizarNivelAutomaticamenteNaGraduacao")
                        .HasColumnType("bit");

                    b.Property<string>("ChecklistAdmissaoPadrao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DiaVencimentoPadrao")
                        .HasColumnType("int");

                    b.Property<int>("DiasAntecedenciaLembrete")
                        .HasColumnType("int");

                    b.Property<int>("DiasToleranciaAtraso")
                        .HasColumnType("int");

                    b.Property<string>("EmailFinanceiro")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EnviarLembreteCobranca")
                        .HasColumnType("bit");

                    b.Property<bool>("GerarMensalidadesAutomaticamente")
                        .HasColumnType("bit");

                    b.Property<string>("MensagemBoasVindasPadrao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NomeEscola")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<decimal>("PercentualJurosMes")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PercentualMultaAtraso")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("PermitirDesligamentoComPendencia")
                        .HasColumnType("bit");

                    b.Property<string>("TelefoneContato")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UltimaAtualizacaoUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ValorMensalidadePadrao")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracoesSistema", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Desconto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Percentual")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal?>("ValorFixo")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateOnly?>("VigenciaFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("VigenciaInicio")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("Descontos", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Desligamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AcessosRemovidos")
                        .HasColumnType("bit");

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DataConfirmacao")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataSolicitacao")
                        .HasColumnType("date");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<decimal>("MultaRescisoria")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PendenciaFinanceira")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("RequerimentoRecebido")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("Desligamentos", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.DocumentoEnvio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArquivoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContentType")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("DocumentoSolicitacaoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnviadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EnviadoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("NomeArquivoOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoSolicitacaoId");

                    b.HasIndex("EnviadoPorUsuarioId");

                    b.ToTable("DocumentoEnvios", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.DocumentoSolicitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DataLimite")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataSolicitacaoUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentoTipoId")
                        .HasColumnType("int");

                    b.Property<string>("ObservacaoAdministrativa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("SolicitadoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataSolicitacaoUtc");

                    b.HasIndex("DocumentoTipoId");

                    b.HasIndex("SolicitadoPorUsuarioId");

                    b.HasIndex("AlunoId", "Status");

                    b.ToTable("DocumentoSolicitacoes", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.DocumentoTipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("DocumentoTipos", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.EventoAlunoPortal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("Fim")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoogleEventoId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Importante")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Local")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.HasKey("Id");

                    b.HasIndex("Tipo");

                    b.HasIndex("Ativo", "Inicio");

                    b.ToTable("EventosAlunoPortal", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.EventoAlunoPortalAlvo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("EventoAlunoPortalId")
                        .HasColumnType("int");

                    b.Property<bool>("Todos")
                        .HasColumnType("bit");

                    b.Property<int?>("TurmaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("TurmaId");

                    b.HasIndex("EventoAlunoPortalId", "AlunoId", "TurmaId", "Todos");

                    b.ToTable("EventosAlunoPortalAlvos", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.ExameGraduacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataExame")
                        .HasColumnType("date");

                    b.Property<string>("Local")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("NivelPretendido")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExamesGraduacao", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.FrequenciaAluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("AulaId")
                        .HasColumnType("int");

                    b.Property<bool>("Justificada")
                        .HasColumnType("bit");

                    b.Property<string>("Justificativa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RegistradoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RegistradoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegistradoPorUsuarioId");

                    b.HasIndex("AlunoId", "Status");

                    b.HasIndex("AulaId", "AlunoId")
                        .IsUnique();

                    b.ToTable("FrequenciasAlunos", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.GoogleAgendaConexao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("AtualizadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ConectadoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("ContaEmail")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Escopos")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RefreshTokenProtegido")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("Ativa");

                    b.HasIndex("ConectadoPorUsuarioId");

                    b.HasIndex("ContaEmail");

                    b.ToTable("GoogleAgendaConexoes", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Graduacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<bool>("CertificadoEmitido")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("DataResultado")
                        .HasColumnType("date");

                    b.Property<int?>("ExameGraduacaoId")
                        .HasColumnType("int");

                    b.Property<int>("NivelAnterior")
                        .HasColumnType("int");

                    b.Property<int?>("NivelNovo")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OmamoriAtualizado")
                        .HasColumnType("bit");

                    b.Property<bool>("ResultadoAprovado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("ExameGraduacaoId");

                    b.ToTable("Graduacoes", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.HistoricoAluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("HistoricoAlunos", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Insignia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Icone")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("RegraAutomatica")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Insignias", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.InventarioItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("AtualizadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AtualizadoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<string>("CodigoInterno")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CriadoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DataAquisicao")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("DisponivelParaAula")
                        .HasColumnType("bit");

                    b.Property<bool>("DisponivelParaEvento")
                        .HasColumnType("bit");

                    b.Property<int>("EstadoConservacao")
                        .HasColumnType("int");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal?>("ValorEstimado")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.HasIndex("AtualizadoPorUsuarioId");

                    b.HasIndex("Categoria");

                    b.HasIndex("CodigoInterno")
                        .IsUnique()
                        .HasFilter("[CodigoInterno] IS NOT NULL");

                    b.HasIndex("CriadoPorUsuarioId");

                    b.HasIndex("Status");

                    b.HasIndex("Tipo");

                    b.HasIndex("Categoria", "Status", "Ativo");

                    b.ToTable("InventarioItens", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.InventarioMovimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFimUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicioUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoogleEventId")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("InventarioItemId")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int?>("ResponsavelUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("TipoMovimentacao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataInicioUtc");

                    b.HasIndex("GoogleEventId");

                    b.HasIndex("InventarioItemId");

                    b.HasIndex("ResponsavelUsuarioId");

                    b.HasIndex("TipoMovimentacao");

                    b.ToTable("InventarioMovimentacoes", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Mensalidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Competencia")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("date");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorBase")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorFinal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId", "Competencia")
                        .IsUnique();

                    b.ToTable("Mensalidades", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<string>("Comprovante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormaPagamento")
                        .HasColumnType("int");

                    b.Property<int>("MensalidadeId")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorPago")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("MensalidadeId");

                    b.ToTable("Pagamentos", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.PermissaoSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<bool>("IsSistema")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Ativo", "IsSistema");

                    b.ToTable("PermissoesSistema", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.RolePermissao", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissaoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataVinculoUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("RoleId", "PermissaoId");

                    b.HasIndex("PermissaoId");

                    b.ToTable("RolesPermissoes", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.RoleSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsSistema")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TipoAcesso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Ativo", "IsSistema");

                    b.HasIndex("TipoAcesso", "Ativo");

                    b.ToTable("RolesSistema", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<string>("Horario")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Modalidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Turmas", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.TurmaHorario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("HoraFim")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<string>("Local")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TurmaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TurmaId", "DiaSemana", "HoraInicio");

                    b.ToTable("TurmaHorarios", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.TurmaInstrutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<bool>("Principal")
                        .HasColumnType("bit");

                    b.Property<int>("TurmaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioSistemaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioSistemaId");

                    b.HasIndex("TurmaId", "UsuarioSistemaId", "DataInicio");

                    b.ToTable("TurmaInstrutores", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.UsuarioPermissao", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("PermissaoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataConcessaoUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UsuarioId", "PermissaoId");

                    b.HasIndex("PermissaoId");

                    b.ToTable("UsuariosPermissoes", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.UsuarioRole", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataVinculoUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UsuarioId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UsuariosRoles", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.UsuarioSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlunoId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataExclusaoUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EmailNormalizado")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Excluido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("ExcluidoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("FotoPerfilUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("IdiomaPreferencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("LoginNormalizado")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("NomeExibicao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("NotificarEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("NotificarSistema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TemaPreferencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("TipoAcesso")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimoLoginUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId")
                        .IsUnique()
                        .HasFilter("[AlunoId] IS NOT NULL");

                    b.HasIndex("EmailNormalizado")
                        .IsUnique()
                        .HasFilter("[EmailNormalizado] IS NOT NULL");

                    b.HasIndex("LoginNormalizado")
                        .IsUnique();

                    b.HasIndex("TipoAcesso", "Ativo");

                    b.ToTable("UsuariosSistema", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.AcordoFinanceiro", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.Aluno", "Aluno")
                        .WithMany("AcordosFinanceiros")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Admissao", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.Aluno", "Aluno")
                        .WithMany("Admissoes")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Aluno", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.Turma", "Turma")
                        .WithMany("Alunos")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.AlunoInsignia", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.Aluno", "Aluno")
                        .WithMany("Insignias")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkkonAdmin.Web.Models.Entities.UsuarioSistema", "ConcedidaPorUsuario")
                        .WithMany()
                        .HasForeignKey("ConcedidaPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IkkonAdmin.Web.Models.Entities.Insignia", "Insignia")
                        .WithMany("Alunos")
                        .HasForeignKey("InsigniaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("ConcedidaPorUsuario");

                    b.Navigation("Insignia");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.AlunoTurma", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.Aluno", "Aluno")
                        .WithMany("AlunoTurmas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkkonAdmin.Web.Models.Entities.Turma", "Turma")
                        .WithMany("AlunoTurmas")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.AuditoriaLog", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.UsuarioSistema", "UsuarioAfetado")
                        .WithMany("LogsComoAfetado")
                        .HasForeignKey("UsuarioAfetadoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IkkonAdmin.Web.Models.Entities.UsuarioSistema", "UsuarioResponsavel")
                        .WithMany("LogsComoAutor")
                        .HasForeignKey("UsuarioResponsavelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("UsuarioAfetado");

                    b.Navigation("UsuarioResponsavel");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Aula", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.UsuarioSistema", "InstrutorUsuario")
                        .WithMany("AulasComoInstrutor")
                        .HasForeignKey("InstrutorUsuarioId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IkkonAdmin.Web.Models.Entities.TurmaHorario", "TurmaHorario")
                        .WithMany("Aulas")
                        .HasForeignKey("TurmaHorarioId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IkkonAdmin.Web.Models.Entities.Turma", "Turma")
                        .WithMany("Aulas")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("InstrutorUsuario");

                    b.Navigation("Turma");

                    b.Navigation("TurmaHorario");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.BlogPost", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.UsuarioSistema", "AuthorUser")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IkkonAdmin.Web.Models.Entities.BlogCategory", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IkkonAdmin.Web.Models.Entities.BlogPost", "TranslationGroupRoot")
                        .WithMany("TranslationVersions")
                        .HasForeignKey("TranslationGroupId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AuthorUser");

                    b.Navigation("Category");

                    b.Navigation("TranslationGroupRoot");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.BlogPostTag", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.BlogPost", "BlogPost")
                        .WithMany("PostTags")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkkonAdmin.Web.Models.Entities.BlogTag", "BlogTag")
                        .WithMany("PostTags")
                        .HasForeignKey("BlogTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogPost");

                    b.Navigation("BlogTag");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Comunicado", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.UsuarioSistema", "CriadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CriadoPorUsuario");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.ComunicadoAlvo", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IkkonAdmin.Web.Models.Entities.Comunicado", "Comunicado")
                        .WithMany("Alvos")
                        .HasForeignKey("ComunicadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkkonAdmin.Web.Models.Entities.Turma", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Aluno");

                    b.Navigation("Comunicado");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.ComunicadoLeitura", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.Aluno", "Aluno")
                        .WithMany("ComunicadosLidos")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkkonAdmin.Web.Models.Entities.Comunicado", "Comunicado")
                        .WithMany("Leituras")
                        .HasForeignKey("ComunicadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Comunicado");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Desconto", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.Aluno", "Aluno")
                        .WithMany("Descontos")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Desligamento", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.Aluno", "Aluno")
                        .WithMany("Desligamentos")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.DocumentoEnvio", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.DocumentoSolicitacao", "DocumentoSolicitacao")
                        .WithMany("Envios")
                        .HasForeignKey("DocumentoSolicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkkonAdmin.Web.Models.Entities.UsuarioSistema", "EnviadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("EnviadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DocumentoSolicitacao");

                    b.Navigation("EnviadoPorUsuario");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.DocumentoSolicitacao", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.Aluno", "Aluno")
                        .WithMany("DocumentosSolicitados")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkkonAdmin.Web.Models.Entities.DocumentoTipo", "DocumentoTipo")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("DocumentoTipoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IkkonAdmin.Web.Models.Entities.UsuarioSistema", "SolicitadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("SolicitadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Aluno");

                    b.Navigation("DocumentoTipo");

                    b.Navigation("SolicitadoPorUsuario");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.EventoAlunoPortalAlvo", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IkkonAdmin.Web.Models.Entities.EventoAlunoPortal", "EventoAlunoPortal")
                        .WithMany("Alvos")
                        .HasForeignKey("EventoAlunoPortalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkkonAdmin.Web.Models.Entities.Turma", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Aluno");

                    b.Navigation("EventoAlunoPortal");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.FrequenciaAluno", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.Aluno", "Aluno")
                        .WithMany("Frequencias")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IkkonAdmin.Web.Models.Entities.Aula", "Aula")
                        .WithMany("Frequencias")
                        .HasForeignKey("AulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkkonAdmin.Web.Models.Entities.UsuarioSistema", "RegistradoPorUsuario")
                        .WithMany()
                        .HasForeignKey("RegistradoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Aluno");

                    b.Navigation("Aula");

                    b.Navigation("RegistradoPorUsuario");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.GoogleAgendaConexao", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.UsuarioSistema", "ConectadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("ConectadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ConectadoPorUsuario");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Graduacao", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.Aluno", "Aluno")
                        .WithMany("Graduacoes")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkkonAdmin.Web.Models.Entities.ExameGraduacao", "ExameGraduacao")
                        .WithMany("Graduacoes")
                        .HasForeignKey("ExameGraduacaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Aluno");

                    b.Navigation("ExameGraduacao");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.HistoricoAluno", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.Aluno", "Aluno")
                        .WithMany("Historicos")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.InventarioItem", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.UsuarioSistema", "AtualizadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("AtualizadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IkkonAdmin.Web.Models.Entities.UsuarioSistema", "CriadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AtualizadoPorUsuario");

                    b.Navigation("CriadoPorUsuario");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.InventarioMovimentacao", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.InventarioItem", "InventarioItem")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("InventarioItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkkonAdmin.Web.Models.Entities.UsuarioSistema", "ResponsavelUsuario")
                        .WithMany()
                        .HasForeignKey("ResponsavelUsuarioId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("InventarioItem");

                    b.Navigation("ResponsavelUsuario");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Mensalidade", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.Aluno", "Aluno")
                        .WithMany("Mensalidades")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Pagamento", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.Aluno", "Aluno")
                        .WithMany("Pagamentos")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IkkonAdmin.Web.Models.Entities.Mensalidade", "Mensalidade")
                        .WithMany("Pagamentos")
                        .HasForeignKey("MensalidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Mensalidade");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.RolePermissao", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.PermissaoSistema", "Permissao")
                        .WithMany("RolePermissoes")
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkkonAdmin.Web.Models.Entities.RoleSistema", "Role")
                        .WithMany("RolePermissoes")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permissao");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.TurmaHorario", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.Turma", "Turma")
                        .WithMany("Horarios")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.TurmaInstrutor", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.Turma", "Turma")
                        .WithMany("Instrutores")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkkonAdmin.Web.Models.Entities.UsuarioSistema", "UsuarioSistema")
                        .WithMany("TurmasComoInstrutor")
                        .HasForeignKey("UsuarioSistemaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Turma");

                    b.Navigation("UsuarioSistema");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.UsuarioPermissao", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.PermissaoSistema", "Permissao")
                        .WithMany("UsuarioPermissoes")
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkkonAdmin.Web.Models.Entities.UsuarioSistema", "Usuario")
                        .WithMany("UsuarioPermissoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permissao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.UsuarioRole", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.RoleSistema", "Role")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkkonAdmin.Web.Models.Entities.UsuarioSistema", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.UsuarioSistema", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.Aluno", "Aluno")
                        .WithOne()
                        .HasForeignKey("IkkonAdmin.Web.Models.Entities.UsuarioSistema", "AlunoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Aluno", b =>
                {
                    b.Navigation("AcordosFinanceiros");

                    b.Navigation("Admissoes");

                    b.Navigation("AlunoTurmas");

                    b.Navigation("ComunicadosLidos");

                    b.Navigation("Descontos");

                    b.Navigation("Desligamentos");

                    b.Navigation("DocumentosSolicitados");

                    b.Navigation("Frequencias");

                    b.Navigation("Graduacoes");

                    b.Navigation("Historicos");

                    b.Navigation("Insignias");

                    b.Navigation("Mensalidades");

                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Aula", b =>
                {
                    b.Navigation("Frequencias");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.BlogCategory", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.BlogPost", b =>
                {
                    b.Navigation("PostTags");

                    b.Navigation("TranslationVersions");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.BlogTag", b =>
                {
                    b.Navigation("PostTags");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Comunicado", b =>
                {
                    b.Navigation("Alvos");

                    b.Navigation("Leituras");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.DocumentoSolicitacao", b =>
                {
                    b.Navigation("Envios");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.DocumentoTipo", b =>
                {
                    b.Navigation("Solicitacoes");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.EventoAlunoPortal", b =>
                {
                    b.Navigation("Alvos");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.ExameGraduacao", b =>
                {
                    b.Navigation("Graduacoes");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Insignia", b =>
                {
                    b.Navigation("Alunos");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.InventarioItem", b =>
                {
                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Mensalidade", b =>
                {
                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.PermissaoSistema", b =>
                {
                    b.Navigation("RolePermissoes");

                    b.Navigation("UsuarioPermissoes");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.RoleSistema", b =>
                {
                    b.Navigation("RolePermissoes");

                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Turma", b =>
                {
                    b.Navigation("AlunoTurmas");

                    b.Navigation("Alunos");

                    b.Navigation("Aulas");

                    b.Navigation("Horarios");

                    b.Navigation("Instrutores");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.TurmaHorario", b =>
                {
                    b.Navigation("Aulas");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.UsuarioSistema", b =>
                {
                    b.Navigation("AulasComoInstrutor");

                    b.Navigation("LogsComoAfetado");

                    b.Navigation("LogsComoAutor");

                    b.Navigation("TurmasComoInstrutor");

                    b.Navigation("UsuarioPermissoes");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
