// <auto-generated />
using System;
using IkkonAdmin.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IkkonAdmin.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260421201908_AddAdminAccessControlAndAudit")]
    partial class AddAdminAccessControlAndAudit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.AcordoFinanceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly?>("FimVigencia")
                        .HasColumnType("date");

                    b.Property<DateOnly>("InicioVigencia")
                        .HasColumnType("date");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorMensalAcordado")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("AcordosFinanceiros", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Admissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlunoId")
                        .HasColumnType("int");

                    b.Property<string>("ChecklistObservacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ContratoAssinado")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("DataAulaExperimental")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataMatricula")
                        .HasColumnType("date");

                    b.Property<bool>("IntegracaoConcluida")
                        .HasColumnType("bit");

                    b.Property<string>("NomeInteressado")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("PagamentoInicialConfirmado")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("Admissoes", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContatoEmergencia")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly>("DataEntrada")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RG")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TurmaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.HasIndex("TurmaId");

                    b.ToTable("Alunos", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.AlunoTurma", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("TurmaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataVinculo")
                        .HasColumnType("datetime2");

                    b.HasKey("AlunoId", "TurmaId");

                    b.HasIndex("TurmaId");

                    b.ToTable("AlunosTurmas", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.AuditoriaLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DadosAntesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DadosDepoisJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataEventoUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("EnderecoIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("EntidadeId")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("UsuarioAfetadoId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioResponsavelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataEventoUtc");

                    b.HasIndex("UsuarioAfetadoId");

                    b.HasIndex("UsuarioResponsavelId");

                    b.HasIndex("Entidade", "Acao");

                    b.ToTable("AuditoriaLogs", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.ConfiguracaoSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AplicarMultaJurosAutomaticamente")
                        .HasColumnType("bit");

                    b.Property<bool>("AtualizarNivelAutomaticamenteNaGraduacao")
                        .HasColumnType("bit");

                    b.Property<string>("ChecklistAdmissaoPadrao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DiaVencimentoPadrao")
                        .HasColumnType("int");

                    b.Property<int>("DiasAntecedenciaLembrete")
                        .HasColumnType("int");

                    b.Property<int>("DiasToleranciaAtraso")
                        .HasColumnType("int");

                    b.Property<string>("EmailFinanceiro")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EnviarLembreteCobranca")
                        .HasColumnType("bit");

                    b.Property<bool>("GerarMensalidadesAutomaticamente")
                        .HasColumnType("bit");

                    b.Property<string>("MensagemBoasVindasPadrao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NomeEscola")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<decimal>("PercentualJurosMes")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PercentualMultaAtraso")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("PermitirDesligamentoComPendencia")
                        .HasColumnType("bit");

                    b.Property<string>("TelefoneContato")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UltimaAtualizacaoUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ValorMensalidadePadrao")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracoesSistema", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Desconto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Percentual")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal?>("ValorFixo")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateOnly?>("VigenciaFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("VigenciaInicio")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("Descontos", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Desligamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AcessosRemovidos")
                        .HasColumnType("bit");

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DataConfirmacao")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataSolicitacao")
                        .HasColumnType("date");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<decimal>("MultaRescisoria")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PendenciaFinanceira")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("RequerimentoRecebido")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("Desligamentos", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.ExameGraduacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataExame")
                        .HasColumnType("date");

                    b.Property<string>("Local")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("NivelPretendido")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExamesGraduacao", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Graduacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<bool>("CertificadoEmitido")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("DataResultado")
                        .HasColumnType("date");

                    b.Property<int?>("ExameGraduacaoId")
                        .HasColumnType("int");

                    b.Property<int>("NivelAnterior")
                        .HasColumnType("int");

                    b.Property<int?>("NivelNovo")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OmamoriAtualizado")
                        .HasColumnType("bit");

                    b.Property<bool>("ResultadoAprovado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("ExameGraduacaoId");

                    b.ToTable("Graduacoes", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.HistoricoAluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("HistoricoAlunos", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Mensalidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Competencia")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("date");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorBase")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorFinal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId", "Competencia")
                        .IsUnique();

                    b.ToTable("Mensalidades", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<string>("Comprovante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormaPagamento")
                        .HasColumnType("int");

                    b.Property<int>("MensalidadeId")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorPago")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("MensalidadeId");

                    b.ToTable("Pagamentos", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.PermissaoSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<bool>("IsSistema")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Ativo", "IsSistema");

                    b.ToTable("PermissoesSistema", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.RolePermissao", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissaoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataVinculoUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("RoleId", "PermissaoId");

                    b.HasIndex("PermissaoId");

                    b.ToTable("RolesPermissoes", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.RoleSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsSistema")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Ativo", "IsSistema");

                    b.ToTable("RolesSistema", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<string>("Horario")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Modalidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Turmas", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.UsuarioPermissao", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("PermissaoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataConcessaoUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UsuarioId", "PermissaoId");

                    b.HasIndex("PermissaoId");

                    b.ToTable("UsuariosPermissoes", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.UsuarioRole", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataVinculoUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UsuarioId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UsuariosRoles", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.UsuarioSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlunoId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataExclusaoUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EmailNormalizado")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Excluido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("ExcluidoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("FotoPerfilUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("IdiomaPreferencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("LoginNormalizado")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("NomeExibicao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("NotificarEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("NotificarSistema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TemaPreferencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("TipoAcesso")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimoLoginUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId")
                        .IsUnique()
                        .HasFilter("[AlunoId] IS NOT NULL");

                    b.HasIndex("EmailNormalizado")
                        .IsUnique()
                        .HasFilter("[EmailNormalizado] IS NOT NULL");

                    b.HasIndex("LoginNormalizado")
                        .IsUnique();

                    b.HasIndex("TipoAcesso", "Ativo");

                    b.ToTable("UsuariosSistema", (string)null);
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.AcordoFinanceiro", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.Aluno", "Aluno")
                        .WithMany("AcordosFinanceiros")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Admissao", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.Aluno", "Aluno")
                        .WithMany("Admissoes")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Aluno", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.Turma", "Turma")
                        .WithMany("Alunos")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.AlunoTurma", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.Aluno", "Aluno")
                        .WithMany("AlunoTurmas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkkonAdmin.Web.Models.Entities.Turma", "Turma")
                        .WithMany("AlunoTurmas")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.AuditoriaLog", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.UsuarioSistema", "UsuarioAfetado")
                        .WithMany("LogsComoAfetado")
                        .HasForeignKey("UsuarioAfetadoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IkkonAdmin.Web.Models.Entities.UsuarioSistema", "UsuarioResponsavel")
                        .WithMany("LogsComoAutor")
                        .HasForeignKey("UsuarioResponsavelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("UsuarioAfetado");

                    b.Navigation("UsuarioResponsavel");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Desconto", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.Aluno", "Aluno")
                        .WithMany("Descontos")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Desligamento", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.Aluno", "Aluno")
                        .WithMany("Desligamentos")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Graduacao", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.Aluno", "Aluno")
                        .WithMany("Graduacoes")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkkonAdmin.Web.Models.Entities.ExameGraduacao", "ExameGraduacao")
                        .WithMany("Graduacoes")
                        .HasForeignKey("ExameGraduacaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Aluno");

                    b.Navigation("ExameGraduacao");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.HistoricoAluno", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.Aluno", "Aluno")
                        .WithMany("Historicos")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Mensalidade", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.Aluno", "Aluno")
                        .WithMany("Mensalidades")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Pagamento", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.Aluno", "Aluno")
                        .WithMany("Pagamentos")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IkkonAdmin.Web.Models.Entities.Mensalidade", "Mensalidade")
                        .WithMany("Pagamentos")
                        .HasForeignKey("MensalidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Mensalidade");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.RolePermissao", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.PermissaoSistema", "Permissao")
                        .WithMany("RolePermissoes")
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkkonAdmin.Web.Models.Entities.RoleSistema", "Role")
                        .WithMany("RolePermissoes")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permissao");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.UsuarioPermissao", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.PermissaoSistema", "Permissao")
                        .WithMany("UsuarioPermissoes")
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkkonAdmin.Web.Models.Entities.UsuarioSistema", "Usuario")
                        .WithMany("UsuarioPermissoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permissao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.UsuarioRole", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.RoleSistema", "Role")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkkonAdmin.Web.Models.Entities.UsuarioSistema", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.UsuarioSistema", b =>
                {
                    b.HasOne("IkkonAdmin.Web.Models.Entities.Aluno", "Aluno")
                        .WithOne()
                        .HasForeignKey("IkkonAdmin.Web.Models.Entities.UsuarioSistema", "AlunoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Aluno", b =>
                {
                    b.Navigation("AcordosFinanceiros");

                    b.Navigation("Admissoes");

                    b.Navigation("AlunoTurmas");

                    b.Navigation("Descontos");

                    b.Navigation("Desligamentos");

                    b.Navigation("Graduacoes");

                    b.Navigation("Historicos");

                    b.Navigation("Mensalidades");

                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.ExameGraduacao", b =>
                {
                    b.Navigation("Graduacoes");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Mensalidade", b =>
                {
                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.PermissaoSistema", b =>
                {
                    b.Navigation("RolePermissoes");

                    b.Navigation("UsuarioPermissoes");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.RoleSistema", b =>
                {
                    b.Navigation("RolePermissoes");

                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.Turma", b =>
                {
                    b.Navigation("AlunoTurmas");

                    b.Navigation("Alunos");
                });

            modelBuilder.Entity("IkkonAdmin.Web.Models.Entities.UsuarioSistema", b =>
                {
                    b.Navigation("LogsComoAfetado");

                    b.Navigation("LogsComoAutor");

                    b.Navigation("UsuarioPermissoes");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
